### ISSUE TITLE
The default quote character is not "

### ISSUE THREAD

**Issue by klatter** [ArjenLammers/csv-connector#12]
Hi Arjen,

First of all great module with a nice performance.
While implementing I noticed that the description of "ImportCSV" java action is out of date.
The library default quote and escape character in the description do not match the implementation.

My suggestion would be to use the NO_QUOTE_CHARACTER/NO_ESCAPE_CHARACTER, such that this matches passing 'empty' as an argument in the java action.

Kind regards,

Nils

https://github.com/ArjenLammers/csv-connector/blob/aaea3cb4c7b5dbae7c9019621c88b37fa44996d2/javasource/csv/actions/ImportCSV.java#L73

**Comment by ArjenLammers** [comment]
Hi @klatter , I have changed the behavior consistently that an empty value leads to a NO_CHARACTER configuration of the library, in 1.12.

Kind regards,
Arjen Lammers
