### ISSUE TITLE
SAST Finding

### ISSUE THREAD

**Issue by al-haras** [ArjenLammers/csv-connector#13]
Hello,

I wanted to reach out regarding a finding in SonarQube for this project to help determine if this is an actual finding or a false positive. Normally, I would reach out to Mendix Support but this is a Community supported module. Is there a specific way you'd like me to relay the finding for further discussion?

**Comment by ArjenLammers** [comment]
hi @al-haras you can contact me directly on the Mendix Community Slack if you want to.
