### ISSUE TITLE
App not able to compile after installing

### ISSUE THREAD

**Issue by JPhomma** [ArjenLammers/csv-connector#14]
**Mx Version: 8.18.14**

After installing the module from the app store, I'm seeing the following Java compile errors:
Buildfile: C:\Users\Jounior.Phomma\{Application Name}\deployment\build_core.xml

compile:
    [javac] Compiling 14 source files to C:\Users\Jounior.Phomma\{Application Name}\deployment\run\bin
    [javac] C:\Users\Jounior.Phomma\{Application Name}\javasource\csv\actions\ExportOQLToCSV.java:35: error: package oql.implementation does not exist
    [javac] import oql.implementation.OQL;
    [javac]                          ^
    [javac] 1 error

BUILD FAILED
C:\Users\Jounior.Phomma\{Application Name}\deployment\build_core.xml:29: Compile failed; see the compiler error output for details.

Total time: 3 seconds

If I remove the module my app loads fine.

**Comment by ArjenLammers** [comment]
Hi @JPhomma , the CSV module depends on the OQL module.
If you import this module, you should be fine.

Kind regards,
Arjen Lammers
