### ISSUE TITLE
Module doesn't work anymore with Mendix Version 9.24.11

### ISSUE THREAD

**Issue by FlyQrcn** [ArjenLammers/csv-connector#18]
Hi,

the module worked perfectly fine up until my upgrade from Mendix 9.18.4 to 9.24.11. I already upgraded the CSV and the OQL Module to the latest releases, but it still shows me following error:
com.mendix.webui.WebUIException: Attempt to illegally add an object to the state with id '50665495808084976'
at com.mendix.webui.requesthandling.helpers.StateHandling.$anonfun$addObjectsToState$1(StateHandling.scala:133)

Could you please advise?

Cheers 
Fulya

**Comment by patrickverhoevenappronto** [comment]
Is this problem solved?
