### ISSUE TITLE
read line removes backslashes

### ISSUE THREAD

**Issue by ginoeelen** [ArjenLammers/csv-connector#3]
I wanted to use the CSV module to import regular expressions, but the read next line action removes all backslashes from the values.

The values are unquoted in my csv file, e.g. 
BE;Belgium;^\d{4}$;1234

in the result, the third column is imported as ^d{4}$ which alters the regex expression.

**Comment by ArjenLammers** [comment]
you might be using a \ as an escape character.
is that the case?
