### ISSUE TITLE
If the attribute is of type Datetime, the value output to CSV is different when using OQL and when using SQL.

### ISSUE THREAD

**Issue by a-takashima-k** [ArjenLammers/csv-connector#7]
I have tried CSV output with ExportOQLToCSV and ExportSQLToCSV respectively.
When I try to output Datetime type, I get different numbers for the same data.
When I checked the values, they differed only by the time zone offset of the execution environment.

I think that different data handling in the same module is a source of confusion and should be unified.

**Comment by ArjenLammers** [comment]
Hi a-takashima-k,

Could you please provide a test setup / project so I can reproduce, test / fix this?

Kind regards,
Arjen Lammers

**Comment by a-takashima-k** [comment]
Hi ArjenLammers.

I attached the mpk file.([CSVExportSampleApp.zip](https://github.com/ArjenLammers/csv-connector/files/7616316/CSVExportSampleApp.zip))
Reproduction The procedure is as follows.
1. set the DB to be used in Project > Settings (I am using PostgreSQL 9.6).
2. Run Locally.
3. Register data from the DataGrid.
4. Press the 'Export CSV from OQL' and 'Export CSV from SQL' buttons to download the CSV.

Open the file and you will see that different values are output for each.

**Comment by ArjenLammers** [comment]
This should be fixed in release 1.10 which is published in the App Store.
