### ISSUE TITLE
Missing value parameter 'characterSet' of call Java action activity 'Export CSV'

### ISSUE THREAD

**Issue by markosmendix** [ArjenLammers/csv-connector#8]
Dear Arjen,

Just upgraded from version 1.8.0 to version 1.9.1 in my Mendix project.

I then need to 'refresh my parameter mapping'.
However, an error on the characterset remains for all my 'Export CSV' actions.
Could you check the specific Export action?

Thanks!

Kind regards,
Mark

**Comment by ArjenLammers** [comment]
Hi Mark,

If the parameters have been changed, you do have to change the calls to the action to fit the appropriate new arguments.
Could you be a bit more specific why you can't cope with this?

Kind regards,
Arjen Lammers

**Comment by markosmendix** [comment]
Hi Arjen,

Sure.
The calls are automatically changed when importing the project and all calls to the action seem legit. Only there is still 1 error left in my console.

I tried to create a whole new 'Export CSV' action in a microflow but this even created 3 errors in my console I could not solve.
Does this give you enough information or would it help for you if I create a demo Mendix project?

Cheers,
Mark

**Comment by ArjenLammers** [comment]
Hi Mark,

Could you tell me which error you're having?

Kind regards,
Arjen Lammers

**Comment by markosmendix** [comment]
Hi Arjen,

I found out the cause, I have been mixing Mx9 and Mx8 versions...

v1.8.0 works fine on Mx 9.6.3. but v1.9.1 doesn't. But that they are not yet compatible with Mx9 is also stated in your documentation. 
No need to further investigate, I will wait untill the new Mx9 version is released.

Cheers,
Mark

**Comment by ArjenLammers** [comment]
Hi Mark,

Where is that actually stated?
I'm not aware that the CSV module is not compatible with a Mendix 9 version.

Kind regards,
Arjen Lammers

**Comment by markosmendix** [comment]
Hi Arjen,

From the marketplace in the studio pro modeler I assumed it is compatible up to 8.12.0.
However, the browser marketplace (https://marketplace.mendix.com/link/component/108605) states it is compatible as: 'Requires 8.12.0 or higher'.

So should work in Mx9 then.
The error I get after upgrading in Mx 9.6.3 to CSV v1.9.1:
1. Parameter mapping needs to be refreshed
2. After refreshing still one error left that I cannot fix -->
Message: Missing value
Element: Parameter 'characterSet' of Java action activity 'Export CSV'

Kind regards,
Mark Peeters

**Comment by ArjenLammers** [comment]
Hi Mark,

It is indeed correct that the characterSet is a new parameter in this version.
But if you would provide it a value (like UTF-8 or just empty) this error should be gone.
If not, this is probably a bug in Studio Pro and you should rather submit a ticket at Mendix Support for it.

Kind regards,
Arjen Lammers

**Comment by markosmendix** [comment]
Hi Arjen,

Ahaa, yes that was it!
When updating the widget, a scroll bar appears on the right (missed this at first) and quotecharacter, escapecharacter and character set are added below as parameters. Quote character and escape character are automatically set to empty but characterset I have to set to empty manually.

Thanks for looking into this Arjen!

Cheers,
Mark
